collective: ionide
tiers:
  - tiers: '*'
    labels: ['backer']
    message: |
      Hey <author> :wave:,

      Thanks for backing our project. If possible, We will handle your
      issue with priority support. To make sure we don't forget how special
      you are, we added a `backer` label to your issue.

      Thanks again for backing us :tada:!
  - tiers: ['Bronze Sponsor', 'Silver Sponsor', 'Gold Sponsor', 'Base Support Sponsor']
    labels: ['sponsor']
    message: |
      Hey <author> :wave:,

      Thanks for backing our project. If possible, We will handle your
      issue with priority support. To make sure we don't forget how special
      you are, we added a `sponsor` label to your issue.

      Thanks again for backing us :tada:!
invitation: |
  Hey <author> :wave:,

  Thank you for opening an issue. We will get back to you as
  soon as we can. Also, check out our OpenCollective and consider
  backing us.

  <link>

  > PS.: We offer `backer` support for all backers. Don't forget to add `backer` label when you start backing us :smile:
